### ISSUE TITLE
i18n todo

### ISSUE THREAD

**Issue by nicHoch** [theCrag/mobile#10]
- [ ] review download and update process of languages
- [ ] review all keys
- [ ] align keys with webSide defaults
- [ ] extract subset of translations from webSide  
- [ ] review spacial fonts (Asian ..)
